### ISSUE TITLE
USER STORY:  User login or logout

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#10]
As a **Site User** I can **login or logout to my registered account** so that **I can view my profile and access my personal account information.**

### Acceptance Criteria
* Login and logout functionality is clearly accessible.
* Users should be able to log in using their registered credentials.
* Users should be able to easily log out.
* Unsuccessful login attempts should provide clear error messages.
*  Post-logout, the user should not have access to profile-specific functionalities without logging in again.

### Tasks
- [ ] Implement login and logout functionality.
- [ ] Invalid login attempts should display an error message without. revealing which field (username or password) is incorrect.
- [ ] Successful login should redirect the user to the homepage.
- [ ] Add confirmation page, if user wants to logout.
- [ ] Provide feedback for logout success.
- [ ] Test the functionality.
