### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#11]
As a **Site User** I can **have my own user profile** so that **I can view my personal order history, update my contact or payment information.**

### Acceptance Criteria
* Users can view their order history and current order status.
* Users can update their contact and payment information from their profile.

### Tasks
- [ ] Create a user profile management section.
- [ ] Implement functionality to display order history.
- [ ] Allow users to edit their contact and payment details.
