### ISSUE TITLE
USER STORY: Products View

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#2]
As a **Shopper** I can **view a list of products** so that can **select some to purchase.**

### Acceptance Criteria
* The web page should display a list of all available products.
* Each card with product in the list must include a clickable button, to its full content.
* Ensure the product listing page is responsive and accessible.

### Tasks
- [ ] Design and implement the product list view in HTML/CSS.
- [ ] Create a responsive layout for displaying products.
- [ ] Integrate backend logic to fetch and display products.
- [ ] Test the functionality.
