### ISSUE TITLE
USER STORY: View Blog Posts

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#6]
As a **Site User** I can **view the site owner's blog post** so that **I can get the latest information about tips and trends.**

### Acceptance Criteria
* Blog posts are accessible from the main navigation.
* Posts display the publication date, author, and categorized tags.

### Tasks
- [ ] Create a button in the navbar to give an access to the blog section.
- [ ] Integrate backend logic to fetch and display recipes.
- [ ] Test the functionality.
