### ISSUE TITLE
USER STORY: Contact Luminique Store

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#7]
As a **Site User,** I can **contact Luminique Store in an easy way** so that I can **interact with them if I need to.**

### Acceptance Criteria
* A contact form is easily accessible from the main navigation or footer.
* Confirmation is provided upon successful submission.

### Tasks
- [ ] Design and implement a contact form.
- [ ] Set up backend support for form submission handling.
- [ ] Implement a confirmation message or page after form submission.
