### ISSUE TITLE
USER STORY: Review a product

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#8]
As a **Site User** I can **leave a review about a product to ensure** that it can **be seen by other site visitors as well as the owner of the online store.**

### Acceptance Criteria
* Users can submit reviews for products they have purchased.
* Reviews are visible on the product detail page.

### Tasks
- [ ] Create a review submission feature on the product detail page.
- [ ] Implement a review model in the backend to store user reviews.
- [ ] Display user reviews on the product detail page.
