### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/luminique_store#9]
As a **Site User** I can **easily register for an account** so that I can **have a personal account.**

### Acceptance Criteria
* A registration form is available and includes fields for username, email, and password.
* Users receive feedback on successful registration or errors.
 
### Tasks
- [ ] Design and implement a user registration form.
- [ ] Set up backend user authentication system.
- [ ]  Test the functionality
